required = [
  "github.com/qubitdigital/baton-api/client",
]

ignored = [
  "github.com/qubitdigital/baton-api",
]

[[constraint]]
  name = "github.com/18F/hmacauth"
  version = "1.0.1"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/bmizerany/assert"

[[constraint]]
  branch = "master"
  name = "github.com/mreiferson/go-options"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.9.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.2"
